print("1 * 0 = ", 1*0)
print("1 * 1 = ", 1*1)
print("1 * 2 = ", 1*2)
print("1 * 3 = ", 1*3)
print("1 * 4 = ", 1*4)
print("1 * 5 = ", 1*5)
print("1 * 6 = ", 1*6)
print("1 * 7 = ", 1*7)
print("1 * 8 = ", 1*8)
print("1 * 9 = ", 1*9)
print("1 * 10 = ", 1*10)
#Declaração de Variáveis
numero = 5
print(numero)
print(f'{numero} * 0 = {numero*0}')
print(f'{numero} * 1 = {numero*1}')
print(f'{numero} * 2 = {numero*2}')
print(f'{numero} * 3 = {numero*3}')
print(f'{numero} * 4 = {numero*4}')
print(f'{numero} * 5 = {numero*5}')
print(f'{numero} * 6 = {numero*6}')
print(f'{numero} * 7 = {numero*7}')
print(f'{numero} * 8 = {numero*8}')
print(f'{numero} * 9 = {numero*9}')
print(f'{numero} * 10 = {numero*10}')